server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study-demo
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml