server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study-demo
    username: root
    password: 123456
  rabbitmq:
    host:
    port: 9002
    virtual-host: my_vhost
    username: admin
    password: adminand123

mybatis:
  mapperLocations: classpath:mapper/*.xml

# Kafka Producer
kafka:
  producer:
    servers: "192.1.136.119:9092"
    retries: 0
    batch:
      size: 16384
    linger: 1
    buffer:
      memory: 33554432

---
# Kafka Consumer
kafka:
  consumer:
    servers: "192.1.136.119:9092"
    enable:
      auto:
        commit: false
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: earliest
    group.id: group-300
    concurrency: 1