server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://minalz:10000/study-demo
    username: root
    password: root

---
spring:
  rabbitmq:
    host: 42.192.138.215
    port: 5672
    username: admin
    password: 123456
    # 消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
# ------ rabbitmq的配置 ------
#  rabbitmq:
#    host:
#    port: 9002
#    virtual-host: my_vhost
#    username: admin
#    password: adminand123
# ------ rabbitmq的配置 ------

mybatis:
  mapperLocations: classpath:mapper/*.xml

# ------ Kafka的配置 ------
# Kafka Producer
#kafka:
#  producer:
#    servers: "192.168.56.101:9092,192.168.56.102:9092,192.168.56.103:9092"
#    retries: 0
#    batch:
#      size: 16384
#    linger: 1
#    buffer:
#      memory: 33554432
#  receive:
#    topic: kafka-test
#    group: kafka-300

---
# Kafka Consumer
#kafka:
#  consumer:
#    servers: "192.168.56.101:9092,192.168.56.102:9092,192.168.56.103:9092"
#    enable:
#      auto:
#        commit: false
#    session:
#      timeout: 6000
#    auto:
#      commit:
#        interval: 100
#      offset:
#        reset: earliest
#    group.id: kafka-300
#    concurrency: 1
# ------ Kafka的配置 ------