server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study-demo
    username: root
    password: 123456
  rabbitmq:
    host:
    port: 9002
    virtual-host: my_vhost
    username: admin
    password: adminand123

mybatis:
  mapperLocations: classpath:mapper/*.xml